### ISSUE TITLE
num_frame in the test config file

### ISSUE THREAD

**Issue by GraceZhuuu** [yzbouc/UVEB#12]
```
python basicsr/test.py -opt options/test/Deblur/test_Deblur_GOPRO.yml
cd results
```

```
datasets:
  test_1:  # the 1st test dataset
    name: GOPRO
    type: VideoRecurrentSplitClipsTestDataset
    dataroot_gt: /media/june/WD10T/UVEB/test/blur
    dataroot_lq: /media/june/WD10T/UVEB/test/blur
    cache_data: False
    io_backend:
      type: disk

    num_frame: 1
    num_overlap: 0
```

the `num_frame` in test_Deblur_GOPRO.yml is set to 1, is that correct ?
